openapi: 3.0.0
info:
  title: Task Mangement System
  description: Documentation for all backend apis
  version: 1.0.0

paths:
  /auth/signup:
    post:
      description: Register user
      requestBody: 
        required: true
        content:
         application/json:
          schema:
            type: object
            properties:
            firstName:
                type: string
                example: hadi
              lastName:
                type: string
                example: noureddine
              userName:
                type: string
                example: hadi.noureddine
              email:
              type: string
              example: hadi@gmail.com
              password:
                type: string
                example: Password123 
              role:
               type: string
               example: admin
      responces:
     201:
          description: User added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: h1g23jhg12g3
  /auth/signin:
   post:
      description: signin user
      requestBody: 
        required: true
        content:
         application/json:
          schema:
            type: object
            properties:
              userName:
                type: string
                example: hadi.noureddine
                password:
                type: string
                example: Password123 
              
      responces:
     201:
          description: User added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: h1g23jhg12g3
/tasks:
  post:
  get:
/tasks/:id:
get:
put:
delete:
/users/:id:
get:
put:
delete:  